// ...existing code...
using SSBJr.ndb.integration.Web.Web.Services;
// ...existing code...
var builder = WebApplication.CreateBuilder(args);
// ...existing code...
builder.Services.AddSingleton<DockerService>();
// ...existing code...
